common: &default_settings
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  pool: 50
  username: root  
  password: m0nsterbid

development:
  <<: *default_settings
  database: activeresource_dev

test:
  <<: *default_settings
  database: activeresource_test

production:
  <<: *default_settings
  database: activeresource_production
