# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37c5edfcffeef6e8d028f5b224b84b26aafff26da0eee925b9631f76d7a4f8e27eb0f647b206fb48749eb9538af429f5001c96c27318df698358d017995c4ad7

test:
  secret_key_base: bc12c9bf7099c47be0bf404720187ac6143be6dd3880e1546fd171512c347aafdfc22a36c186f7c226d87b58865cd0b63299515d12df951a8b6a98bc5ca3f829

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
